# permissions for end users to edit servicemetadatawatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicemetadatawatcher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-registry
    app.kubernetes.io/part-of: cluster-registry
    app.kubernetes.io/managed-by: kustomize
  name: servicemetadatawatcher-editor-role
rules:
- apiGroups:
  - registry.ethos.adobe.com
  resources:
  - servicemetadatawatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.ethos.adobe.com
  resources:
  - servicemetadatawatchers/status
  verbs:
  - get
